Repository Young-Season/Young_Backend, pull requests merged in 2023-12, with the labels that each got.

#3 chore: db 연결 및 테스트
  .gitignore
  README.md
  config/baseResponseStatus.js
  config/express.js
  config/firebase.js
  config/winston.js
  index.js
  package-lock.json
  package.json
  src/app/User/userController.js
  src/app/User/userDao.js
  src/app/User/userDto.js
  src/app/User/userProvider.js
  src/app/User/userRoute.js
  src/app/User/userService.js
Labels: enhancement

#4 chore: mongoDB 연결 및 test api 작성
  config/database.js
  config/firebase.js
  index.js
  package-lock.json
  package.json
  src/app/User/userController.js
  src/app/User/userDao.js
  src/app/User/userDto.js
  src/app/User/userProvider.js
  src/models/user.js
Labels: enhancement

#8 feat/#7: 카카오 로그인
  config/baseResponseStatus.js
  package-lock.json
  package.json
  src/app/User/userController.js
  src/app/User/userDao.js
  src/app/User/userProvider.js
  src/app/User/userRoute.js
  src/app/User/userService.js
  src/models/user.js
Labels: feat

#12 feat: friend 모델 추가
  config/baseResponseStatus.js
  src/app/User/userController.js
  src/app/User/userDao.js
  src/app/User/userProvider.js
  src/app/User/userRoute.js
  src/app/User/userService.js
  src/models/friend.js
  src/models/user.js
Labels: enhancement

#14 feat: descriptions model + cors
  config/express.js
  src/app/User/userController.js
  src/app/User/userDao.js
  src/app/User/userProvider.js
  src/app/User/userRoute.js
  src/models/description.js
  src/models/friend.js
  src/models/user.js
Labels: enhancement

#16 Feat/#15 results
  config/baseResponseStatus.js
  src/app/User/userController.js
  src/app/User/userDao.js
  src/app/User/userProvider.js
  src/app/User/userRoute.js
  src/app/User/userService.js
  src/models/friend.js
  src/models/user.js
  src/utils/encryption.js
Labels: feat, fix

#17 feat: 호스트 결과 조회
  src/app/User/userController.js
  src/app/User/userDao.js
  src/app/User/userProvider.js
  src/app/User/userRoute.js
  src/models/description.js
Labels: enhancement

#18 Data/#3
  config/baseResponseStatus.js
  package-lock.json
  package.json
  src/app/User/userController.js
  src/app/User/userDao.js
  src/app/User/userProvider.js
  src/app/User/userRoute.js
  src/app/User/userService.js
  src/models/user.js
Labels: enhancement

#22 feat/#13: jwt 인가 구현
  src/app/User/userController.js
Labels: enhancement

#26 refactor/#25: 아이디 암호화 추가
  src/app/User/userController.js
  src/app/User/userDao.js
  src/app/User/userProvider.js
  src/utils/encryption.js
Labels: enhancement
